//! Broadcast channel for ceremony state transitions.
//!
//! Subscribers (TUI, future GUI clients, hooks) react to:
//! - tablet generation
//! - item updates (patch / add / done toggle)
//! - diary upserts
//! - pattern detections
//! - priority confirmations (weekly only)
//!
//! Backed by `tokio::sync::broadcast` so multiple subscribers can
//! attach without serialising. Dropped events (slow consumer) are
//! logged but never bubble; subscribers can call `resubscribe` to
//! resync. The binary's WS layer is the canonical subscriber that
//! forwards events to clients.

use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;

/// Default broadcast channel capacity. Same order-of-magnitude as
/// `LocalService::notice_tx` (64). Picked so a burst of pattern
/// detections during a retro run doesn't drop on a single slow
/// subscriber.
pub const DEFAULT_CAPACITY: usize = 64;

/// All ceremony state-change events. New variants are additive —
/// existing subscribers can ignore unknown variants.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "event", content = "data")]
pub enum CeremonyEvent {
    /// A new tablet was generated by the dispatcher.
    TabletGenerated {
        tablet_id: String,
        kind: String,
        period_key: String,
    },
    /// An item row was inserted or modified (toggle done, edit body,
    /// add user item).
    ItemUpdated {
        item_id: String,
        tablet_id: String,
    },
    /// User wrote or replaced the diary body on a retro tablet
    /// (fired by `ceremonies.upsert_diary` — T-0289).
    DiaryUpdated { tablet_id: String },
    /// A pattern row was written during pattern detection.
    PatternDetected {
        pattern_id: String,
        iso_week: String,
        pattern_key: String,
    },
    /// A weekly priority was confirmed (fired by T-0042's
    /// `confirm_priority` action, not this initiative).
    PriorityConfirmed { priority_id: String },
}

/// Sender side of the broadcast channel. Clone to share across the
/// dispatcher, service, and any plugin that wants to emit.
pub type CeremonyEventSender = broadcast::Sender<CeremonyEvent>;

/// Receiver side. Subscribers call `subscribe()` on a sender to
/// obtain one. Bound to a single subscriber — clone the sender,
/// not the receiver, to add new subscribers.
pub type CeremonyEventReceiver = broadcast::Receiver<CeremonyEvent>;

/// Build a fresh event channel with the default capacity. Used by
/// callers that don't already have a sender to clone from
/// (tests, top-level wiring).
pub fn channel() -> (CeremonyEventSender, CeremonyEventReceiver) {
    broadcast::channel(DEFAULT_CAPACITY)
}

/// Send an event, swallowing the "no subscribers" error. The send
/// surface is best-effort: a broadcast channel with no listeners
/// returns `Err` from `send`, but that's an expected state for a
/// process that hasn't wired the WS subscriber yet.
pub fn emit(sender: &CeremonyEventSender, event: CeremonyEvent) {
    let _ = sender.send(event);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn tablet_generated_round_trips() {
        let (tx, mut rx) = channel();
        emit(
            &tx,
            CeremonyEvent::TabletGenerated {
                tablet_id: "retro-2026-W20".into(),
                kind: "retro".into(),
                period_key: "2026-W20".into(),
            },
        );
        let received = rx.recv().await.unwrap();
        assert!(matches!(
            received,
            CeremonyEvent::TabletGenerated { ref tablet_id, .. } if tablet_id == "retro-2026-W20"
        ));
    }

    #[tokio::test]
    async fn item_updated_serialises_as_tagged_json() {
        let event = CeremonyEvent::ItemUpdated {
            item_id: "item-1".into(),
            tablet_id: "retro-2026-W20".into(),
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"event\":\"ItemUpdated\""));
        assert!(json.contains("\"data\":{"));
    }

    #[tokio::test]
    async fn emit_with_no_subscribers_is_silent() {
        let (tx, rx) = channel();
        drop(rx);
        // No panic, no error bubbled.
        emit(
            &tx,
            CeremonyEvent::DiaryUpdated {
                tablet_id: "retro-2026-W20".into(),
            },
        );
    }

    #[tokio::test]
    async fn two_subscribers_each_receive() {
        let (tx, mut rx1) = channel();
        let mut rx2 = tx.subscribe();
        emit(
            &tx,
            CeremonyEvent::PatternDetected {
                pattern_id: "p-1".into(),
                iso_week: "2026-W20".into(),
                pattern_key: "rollover_heat".into(),
            },
        );
        let a = rx1.recv().await.unwrap();
        let b = rx2.recv().await.unwrap();
        assert_eq!(a, b);
    }
}
